-- =====================================================
-- E-COMMERCE SALES ANALYTICS
-- Intermediate SQL Queries
-- Dataset: ecommerce_sales
-- =====================================================


-- =====================================================
-- Q31. Classify each order based on its revenue:
--      < 500      → Low
--      500–1500   → Medium
--      > 1500     → High
--
-- Concept: CASE WHEN
-- =====================================================

SELECT
    order_id,
    revenue,
    CASE
        WHEN revenue < 500 THEN 'Low'
        WHEN revenue BETWEEN 500 AND 1500 THEN 'Medium'
        WHEN revenue > 1500 THEN 'High'
    END AS revenue_category
FROM ecommerce_sales;


-- =====================================================
-- Q32. Calculate the pre-discount value of each order.
--
-- Formula:
-- Pre-discount value = quantity × unit_price
--
-- Concept: Arithmetic calculation
-- =====================================================

SELECT
    order_id,
    quantity,
    unit_price,
    quantity * unit_price AS pre_discount_value
FROM ecommerce_sales;


-- =====================================================
-- Q33. Calculate the discount amount for each order.
--
-- Formula:
-- Discount amount =
-- (quantity × unit_price × discount) / 100
--
-- Concept: Arithmetic calculation
-- =====================================================

SELECT
    order_id,
    quantity,
    unit_price,
    discount,
    (quantity * unit_price) * discount / 100 AS discount_amount
FROM ecommerce_sales;


-- =====================================================
-- Q34. Which product categories generated more than
-- ₹1,000,000 in total revenue?
--
-- Concept: GROUP BY + SUM() + HAVING
-- =====================================================

SELECT
    product_category,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY product_category
HAVING total_revenue > 1000000;


-- =====================================================
-- Q35. Which regions have more than 1,200 orders?
--
-- Concept: GROUP BY + COUNT() + HAVING
-- =====================================================

SELECT
    region,
    COUNT(*) AS total_orders
FROM ecommerce_sales
GROUP BY region
HAVING total_orders > 1200;


-- =====================================================
-- Q36. Which payment methods generated more than
-- ₹1,500,000 in total revenue?
--
-- Concept: GROUP BY + SUM() + HAVING
-- =====================================================

SELECT
    payment_method,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY payment_method
HAVING total_revenue > 1500000;


-- =====================================================
-- Q37. What is the earliest order date in the dataset?
--
-- Concept: MIN()
-- =====================================================

SELECT
    MIN(order_date) AS earliest_order_date
FROM ecommerce_sales;


-- =====================================================
-- Q38. What is the latest order date in the dataset?
--
-- Concept: MAX()
-- =====================================================

SELECT
    MAX(order_date) AS latest_order_date
FROM ecommerce_sales;


-- =====================================================
-- Q39. What is the total revenue generated by year?
--
-- Concept: YEAR() + GROUP BY + SUM()
-- =====================================================

SELECT
    YEAR(order_date) AS order_year,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


-- =====================================================
-- Q40. How many orders were placed in each year?
--
-- Concept: YEAR() + GROUP BY + COUNT()
-- =====================================================

SELECT
    YEAR(order_date) AS order_year,
    COUNT(*) AS total_orders
FROM ecommerce_sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


-- =====================================================
-- Q41. What is the average monthly revenue?
--
-- Concept: MONTH() + GROUP BY + AVG()
-- =====================================================

SELECT
    MONTH(order_date) AS order_month,
    AVG(revenue) AS average_monthly_revenue
FROM ecommerce_sales
GROUP BY MONTH(order_date)
ORDER BY order_month;


-- =====================================================
-- Q42. Which year generated the highest revenue?
--
-- Concept: YEAR() + GROUP BY + SUM()
--          + ORDER BY + LIMIT
-- =====================================================

SELECT
    YEAR(order_date) AS order_year,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY YEAR(order_date)
ORDER BY total_revenue DESC
LIMIT 1;


-- =====================================================
-- Q43. How many orders did each customer place?
--
-- Concept: GROUP BY + COUNT()
-- =====================================================

SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM ecommerce_sales
GROUP BY customer_id;


-- =====================================================
-- Q44. How much total revenue did each customer generate?
--
-- Concept: GROUP BY + SUM()
-- =====================================================

SELECT
    customer_id,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY customer_id;


-- =====================================================
-- Q45. What is the average order value for each customer?
--
-- Concept: GROUP BY + AVG()
-- =====================================================

SELECT
    customer_id,
    AVG(revenue) AS average_order_value
FROM ecommerce_sales
GROUP BY customer_id;


-- =====================================================
-- Q46. Which customers placed more than 5 orders?
--
-- Concept: GROUP BY + COUNT() + HAVING
-- =====================================================

SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM ecommerce_sales
GROUP BY customer_id
HAVING total_orders > 5;


-- =====================================================
-- Q47. Which customers generated more than ₹10,000
-- in total revenue?
--
-- Concept: GROUP BY + SUM() + HAVING
-- =====================================================

SELECT
    customer_id,
    SUM(revenue) AS total_revenue
FROM ecommerce_sales
GROUP BY customer_id
HAVING total_revenue > 10000;


-- =====================================================
-- Q48. How many unique customers are present in each region?
--
-- Concept: GROUP BY + COUNT(DISTINCT)
-- =====================================================

SELECT
    region,
    COUNT(DISTINCT customer_id) AS unique_customers
FROM ecommerce_sales
GROUP BY region
ORDER BY region;